# Python으로 하는 기초 수학
## 행렬

In [3]:
import numpy as np

In [20]:
# 0~17까지의 수 나열
display(np.arange(0, 18))

# 0~17까지의 수를 3행 6열의 직사각형 행렬(장방행렬) 형태로 표현
# 수의 개수와 행렬 성분 개수가 같아야 함
display(np.arange(0, 18).reshape((3, 6)))

# 랜덤한 값으로 만들 수도 있다.
# 0~10까지의 수 중 랜덤으로 3행 4열의 행렬로 표현
display(np.random.randint(0, 10, size=(3, 4)))

# 정사각형 행렬인 정방행렬로 표현
display(np.arange(0, 9).reshape((3, 3)))

# 랜덤한 값으로 정방행렬 표현
np.random.randint(0, 10, size=(4, 4))

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17])

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17]])

array([[9, 0, 0, 9],
       [2, 2, 6, 9],
       [3, 1, 0, 5]])

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

array([[8, 3, 7, 0],
       [0, 3, 8, 9],
       [3, 9, 4, 7],
       [4, 3, 4, 8]])

In [21]:
# 영행렬
np.zeros((4, 4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [25]:
# 항등행렬(단위행렬)
np.identity(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [31]:
# 대각행렬
# 대각행렬은 주대각선 원소를 제외한 모든 원소가 0인 정방행렬
# 영행렬, 단위행렬은 모두 대각행렬에 포함된다.
# 장방행렬 역시 주대각 성분을 제외한 나머지 원소가 0일 경우 대각행렬에 포함된다.

# 대각행렬 만들기
diag = np.diag((4, 2, 2, 5, 1, 6))
display(diag)

# 대각성분 뽑기
display(np.diagonal(diag))

# 대각성분이 1인 행렬 만들기
display(np.eye(4, 4))

# 장방행렬로 만들기
# 직사각형일 경우 부분적으로 만들어진다.
display(np.eye(4, 5))

array([[4, 0, 0, 0, 0, 0],
       [0, 2, 0, 0, 0, 0],
       [0, 0, 2, 0, 0, 0],
       [0, 0, 0, 5, 0, 0],
       [0, 0, 0, 0, 1, 0],
       [0, 0, 0, 0, 0, 6]])

array([4, 2, 2, 5, 1, 6])

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.]])

In [34]:
# 스칼라 행렬
# 주대각 성분이 모두 같은 원소로 된 대각행렬
display(np.identity(4))

# 대각 성분이 모두 같은 대각행렬
np.diag(np.full(4, 5))

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

array([[5, 0, 0, 0],
       [0, 5, 0, 0],
       [0, 0, 5, 0],
       [0, 0, 0, 5]])

In [40]:
# 삼각행렬
# 정방행렬의 특수한 경우로, 주대각선을 기준으로 대각형의 위쪽이나 아래쪽 항들의 값이 모두 0인 행렬
# 상삼각행렬과 하삼각행렬이 있다.

mat = np.arange(0, 25).reshape((5, 5))
display(mat)

# 상삼각행렬
# 0 대신 1~ 이상의 수를 대입할 경우, 점점 0이 아닌 기존의 값으로 채워진다.
display(np.triu(mat, 0))

# 하삼각행렬
np.tril(mat, 0)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

array([[ 0,  1,  2,  3,  4],
       [ 0,  6,  7,  8,  9],
       [ 0,  0, 12, 13, 14],
       [ 0,  0,  0, 18, 19],
       [ 0,  0,  0,  0, 24]])

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [42]:
# 전치행렬
# 주대각 성분을 기준으로 행과 열을 대칭으로 바꾼 행렬
# 주대각 성분을 기준으로 하므로, 주대각 성분은 변하지 않는다.

mat = np.arange(0, 16).reshape((4, 4))
display(mat)

# 전치행렬 만들기
display(mat.T)

# 다른 방법
np.transpose(mat)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

array([[ 0,  4,  8, 12],
       [ 1,  5,  9, 13],
       [ 2,  6, 10, 14],
       [ 3,  7, 11, 15]])

array([[ 0,  4,  8, 12],
       [ 1,  5,  9, 13],
       [ 2,  6, 10, 14],
       [ 3,  7, 11, 15]])

In [44]:
# 직교행렬
# 행렬 A의 역행렬이 A의 전치행렬인 행렬 A
# 직교행렬과 직교행렬의 전치행렬을 행렬곱하면 단위행렬이 나온다.

mat = np.array([[0, 0, 1],[1, 0, 0],[0, 1, 0]])
display(mat)

# 행렬 mat과 전치행렬 mat.T를 행렬곱하였을 때, 단위행렬이 나오는 행렬 
np.dot(mat, mat.T)

array([[0, 0, 1],
       [1, 0, 0],
       [0, 1, 0]])

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])

- 참고링크: https://gooopy.tistory.com/105